apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-ftvl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-ftvl
    app.kubernetes.io/part-of: build-suite-test-application-qyym
  name: build-suite-test-component-git-source-ftvl
  namespace: build-e2e-4bfe2ada-5c95-4db9-8a88-8417c76264e2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-suite-test-component-git-source-ftvl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-suite-test-component-git-source-ftvl
    spec:
      containers:
      - image: quay.io/psturc/test-images:117bf78c842a4426be0ff634f1e57fcd
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
